enum StatusEnums {
  INITIAL_STATE,

  ERROR_STATE,
  LOADING_STATE,

  PRODUCT_LOADED_STATE,
  IMAGE_UPLOADED_STATE,
  IMAGE_UPLOADING_STATE,
  PRODUCT_ADDED_STATE,
  PRODUCT_UPDATED_STATE,
  PRODUCT_DELETED_STATE,
  ORDERS_LOADED_STATE,
  ORDER_STATUS_UPDATED
}
